# Run with command 'docker-compose up --build' to build
# or 'docker-compose up' to start the app
version: '3'
services:
    web:
        image: client
        build: ./client
        ports:
            - '3000:80'
        depends_on:
            - 'api'
        stdin_open: true
    api:
        image: server
        build: ./server
        expose:
            - '5000'
        depends_on:
            - 'mongo'
    mongo:
        image: 'mongo'
