export enum Format {
    FORMIK_DATE_FORMAT = 'YYYY-MM-DD',
    DATE_FORMAT = 'DD/MMM/YYYY',
    EXT_DATE_FORMAT = 'MMMM Do YYYY, h:mm:ss A',
    MONTH_DATE_FORMAT = 'MMMM',
    YEAR_DATE_FORMAT = 'YYYY',
    MONTH_YEAR_FORMAT = 'MMMM YYYY',
}
