const FORMIK_DATE_FORMAT = 'YYYY-MM-DD';
const DATE_FORMAT = 'DD/MMM/YYYY';
const EXT_DATE_FORMAT = 'MMMM Do YYYY, h:mm:ss A';
const MONTH_DATE_FORMAT = 'MMMM';
const YEAR_DATE_FORMAT = 'YYYY';
const MONTH_YEAR_FORMAT = 'MMMM YYYY';

export { FORMIK_DATE_FORMAT, DATE_FORMAT, EXT_DATE_FORMAT, MONTH_DATE_FORMAT, YEAR_DATE_FORMAT, MONTH_YEAR_FORMAT };
