name: boon
region: ams

static_sites:
    - name: landing
      github:
          branch: master
          deploy_on_push: true
          repo: the-dead-planet/BOON
      source_dir: landing
      output_dir: /public
      build_command: npm run ci
      routes:
          - path: /

    - name: client
      github:
          branch: master
          deploy_on_push: true
          repo: the-dead-planet/BOON
      source_dir: client
      output_dir: /build
      build_command: yarn build
      routes:
          - path: /app
