name: boon
region: ams

services:
    - name: server
      github:
          branch: master
          deploy_on_push: true
          repo: the-dead-planet/BOON
      source_dir: server
      build_command: yarn
      run_command: yarn start
      routes:
          - path: /api/

static_sites:
    - name: client
      github:
          branch: master
          deploy_on_push: true
          repo: the-dead-planet/BOON
      source_dir: client
      output_dir: /build
      build_command: yarn build
      routes:
          - path: /
      catchall_document: index.html
