const DRAWER_WIDTH = 240;
const DRAWER_SECONDARY_WIDTH = 400;
const NAVBAR_LEFT_WIDTH = 200;
const TOOLBAR_HEIGHT = 40;
const JUMBOTRON_HEIGHT = '100vh';

export { DRAWER_WIDTH, DRAWER_SECONDARY_WIDTH, NAVBAR_LEFT_WIDTH, TOOLBAR_HEIGHT, JUMBOTRON_HEIGHT };
