# Based on rwakulszowa/container-registry-playground
name: Build-And-Test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    # Run tests.
    # See also https://docs.docker.com/docker-hub/builds/automated-testing/
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

              # Run API tests first. They're simpler and cheaper to build.
            - name: Build api image
              run: docker-compose build api

            - name: Run api unit tests
              run: docker-compose run api yarn test

              # API tests pass. Run the client unit tests.
              # Use docker, instead of docker-compose, because we must specify
              # the target to build.
              # docker-compose would build the default target, which is not
              # feasible for running tests - it only contains the final bundle.
            - name: Build client image
              run: docker build -t client-base client --target base

            - name: Run client unit tests
              run: docker run client-base npm test -- --watchAll=false
